"""empty message

Revision ID: 3c133c8e15ba
Revises: 2787acc0ae99
Create Date: 2019-05-31 02:04:06.814895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c133c8e15ba'
down_revision = '2787acc0ae99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bids', 'transporter_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bids', 'vehicle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'budget',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'distance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'distance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'budget',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bids', 'vehicle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bids', 'transporter_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bids', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
